version: "3"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_DB=sebbia
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
