version: "3"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sebbia
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=123321
    ports:
      - "5432:5432"